# Generated by Django 5.1.4 on 2026-04-10 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('num', 'Тоо'), ('icon', 'Emoji дүрс')], default='num', max_length=10, verbose_name='Төрөл')),
                ('value', models.CharField(max_length=20, verbose_name='Тоо эсвэл emoji')),
                ('label', models.CharField(max_length=120, verbose_name='Тайлбар')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Дараалал')),
            ],
            options={
                'verbose_name': 'About тизер карт',
                'verbose_name_plural': 'About тизер картууд',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BenefitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='Emoji дүрс')),
                ('number', models.CharField(max_length=5, verbose_name='Дугаар (01, 02 …)')),
                ('title', models.CharField(max_length=200, verbose_name='Гарчиг')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Тэгүүд (таслалаар: С Витамин, Иммун систем …)')),
                ('is_reverse', models.BooleanField(default=False, verbose_name='Байрлал урвуу (тийм = зураг баруун талд)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Дараалал')),
            ],
            options={
                'verbose_name': 'Дэлгэрэнгүй ашиг тус (Ашиг тус хуудас)',
                'verbose_name_plural': 'Дэлгэрэнгүй ашиг тусууд',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BenefitTeaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='Emoji дүрс')),
                ('title', models.CharField(max_length=120, verbose_name='Гарчиг')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Дараалал')),
            ],
            options={
                'verbose_name': 'Ашиг тусын товч (нүүр хуудас)',
                'verbose_name_plural': 'Ашиг тусын товч картууд (нүүр хуудас)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='◈', max_length=10, verbose_name='Дүрс')),
                ('title', models.CharField(max_length=120, verbose_name='Гарчиг')),
                ('description', models.CharField(max_length=255, verbose_name='Тайлбар')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Дараалал')),
            ],
            options={
                'verbose_name': 'Онцлог (features strip)',
                'verbose_name_plural': 'Онцлогууд (features strip)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20, verbose_name='Тоо / утга')),
                ('label', models.CharField(max_length=120, verbose_name='Тайлбар')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Дараалал')),
            ],
            options={
                'verbose_name': 'Hero статистик',
                'verbose_name_plural': 'Hero статистикууд',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KeyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20, verbose_name='Тоо / утга (190×, 70+ …)')),
                ('label', models.CharField(max_length=120, verbose_name='Тайлбар')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Дараалал')),
            ],
            options={
                'verbose_name': 'Түлхүүр тоо (Ашиг тус хуудас)',
                'verbose_name_plural': 'Түлхүүр тоонууд',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='Emoji дүрс')),
                ('title', models.CharField(max_length=120, verbose_name='Гарчиг')),
                ('description', models.CharField(max_length=255, verbose_name='Тайлбар')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Дараалал')),
            ],
            options={
                'verbose_name': 'Эрхэм зорилгын утга (Бидний тухай)',
                'verbose_name_plural': 'Эрхэм зорилгын утгууд',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NutrientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=5, verbose_name='Үсэг / тэмдэг (С, Е, Ω …)')),
                ('title', models.CharField(max_length=120, verbose_name='Гарчиг')),
                ('value_text', models.CharField(max_length=120, verbose_name='Утга (695 мг/100г …)')),
                ('note', models.CharField(max_length=255, verbose_name='Тэмдэглэл')),
                ('bar_pct', models.PositiveSmallIntegerField(default=80, verbose_name='Мөрийн % (0-100)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Дараалал')),
            ],
            options={
                'verbose_name': 'Шим тэжээлийн карт (Танилцуулга хуудас)',
                'verbose_name_plural': 'Шим тэжээлийн картууд',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, verbose_name='Дугаар (01, 02 …)')),
                ('icon', models.CharField(max_length=10, verbose_name='Emoji дүрс')),
                ('title', models.CharField(max_length=120, verbose_name='Гарчиг')),
                ('description', models.CharField(max_length=255, verbose_name='Тайлбар')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Дараалал')),
            ],
            options={
                'verbose_name': 'Үйлдвэрлэлийн алхам (Бидний тухай)',
                'verbose_name_plural': 'Үйлдвэрлэлийн алхамууд',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (filter-д ашиглана)')),
            ],
            options={
                'verbose_name': 'Бүтээгдэхүүний ангилал',
                'verbose_name_plural': 'Бүтээгдэхүүний ангилалууд',
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True, verbose_name='Түлхүүр')),
                ('value', models.TextField(verbose_name='Утга')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Тайлбар (admin харуулах нэр)')),
            ],
            options={
                'verbose_name': 'Сайтын текст',
                'verbose_name_plural': 'Сайтын текстүүд',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='UsageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10, verbose_name='Emoji дүрс')),
                ('title', models.CharField(max_length=120, verbose_name='Гарчиг')),
                ('description', models.CharField(max_length=255, verbose_name='Тайлбар')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Дараалал')),
            ],
            options={
                'verbose_name': 'Хэрэглэх арга (Танилцуулга хуудас)',
                'verbose_name_plural': 'Хэрэглэх аргууд',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Үнэ (₮)')),
                ('unit', models.CharField(max_length=50, verbose_name='Хэмжих нэгж (500мл, 50г …)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зураг')),
                ('badge', models.CharField(blank=True, choices=[('', 'Байхгүй'), ('bestseller', 'Bestseller'), ('premium', 'Premium'), ('new', 'Шинэ')], default='', max_length=20, verbose_name='Badge')),
                ('badge_icon', models.CharField(blank=True, max_length=10, verbose_name='Badge emoji (🏆, ⭐ …)')),
                ('nutrients', models.CharField(blank=True, max_length=500, verbose_name='Шим тэжээл (таслалаар тусгаарлана: С Витамин, Омега 3…)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Онцлох бүтээгдэхүүн')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Дараалал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory', verbose_name='Ангилал')),
            ],
            options={
                'verbose_name': 'Бүтээгдэхүүн',
                'verbose_name_plural': 'Бүтээгдэхүүнүүд',
                'ordering': ['order'],
            },
        ),
    ]
