# Generated by Django 5.1.4 on 2026-04-11 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Сессийн түлхүүр')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Утасны дугаар')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='И-мэйл')),
                ('address', models.TextField(verbose_name='Хаяг')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Өргөрөг')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Уртраг')),
                ('note', models.TextField(blank=True, verbose_name='Нэмэлт тайлбар')),
                ('status', models.CharField(choices=[('pending', 'Хүлээгдэж буй'), ('confirmed', 'Баталгаажсан'), ('shipped', 'Хүргэлтэнд'), ('delivered', 'Хүргэгдсэн'), ('cancelled', 'Цуцлагдсан')], default='pending', max_length=20, verbose_name='Төлөв')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Нийт үнэ (₮)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Огноо')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Захиалга',
                'verbose_name_plural': 'Захиалгууд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Тоо ширхэг')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Нэгжийн үнэ (₮)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Бүтээгдэхүүн')),
            ],
            options={
                'verbose_name': 'Захиалгын зүйл',
                'verbose_name_plural': 'Захиалгын зүйлс',
            },
        ),
    ]
