# Generated by Django 5.2.13 on 2026-05-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagecard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='usage_cards/', verbose_name='Зураг (нэн тэргүүн харагдана)'),
        ),
        migrations.AlterField(
            model_name='usagecard',
            name='icon',
            field=models.CharField(blank=True, max_length=10, verbose_name='Emoji дүрс (зураг байхгүй үед харагдана)'),
        ),
    ]
